name: pagy
description: "A Flutter package for easy pagination with API data fetching, customizable UI, shimmer effects, error handling, and smooth scrolling."
version: 0.0.3+1
homepage: https://github.com/hayatkhan67/pagy

environment:
  sdk: ">=3.6.2 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ">=5.2.0 <6.0.0"
  flutter_staggered_grid_view: ">=0.7.0 <1.0.0"
  skeletonizer: ">=1.4.3 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

license: MIT

flutter:
